export const language = {
  delegatedUserRequired: [
    "Delegated user is required",
    "ተወካይ ተጠቃሚ አስፈላጊ ነው",
    "",
    "",
    "",
    "",
  ],
  sharedUserRequired: [
    "shared user is required",
    "ተጋሪ ተጠቃሚ አስፈላጊ ነው",
    "",
    "",
    "",
    "",
  ],
  ////////////////////////////////////////////
  revokeSharing: ["Revoke Sharing", "የመለያ መጋራት ያንሱ", "Dhiisi", "", "", ""],
  users: ["Users", "ተጠቃሚዎች", "", "", "", ""],
  userPositions: ["User Positions", "የስራ ሃላፊነቶች", "", "", "", ""],
  isSensitive: ["Is sensitive", "ሚስጥራዊ", "", "", "", ""],
  searchByPermissionCateogry: [
    "Search by permission category",
    "በፍቃድ መደብ ይፈልጉ",
    "",
    "",
    "",
    "",
  ],
  orgnaizationRequired: [
    "Orgnization is required",
    "ተቋም አስፈላጊ ነው",
    "",
    "",
    "",
    "",
    "",
  ],
  uploadStampImages: ["Upload Stamp", "ማህተም ይጫኑ", "", "", "", ""],
  stampFormat: [
    "You can upload multiple stamp images. Accepted formats: JPG,PNG, TIFF",
    "ከአንድ በላይ ማህተም መጫን ይችላሉ። ተቀባይነት ያላቸው ቅርጸቶች JPG, PNG, TIFF",
  ],
  clickorDragStamp: [
    "Click or drag files to upload stamps",
    "",
    "",
    "",
    "",
    "",
  ],
  stampPreview: ["Stamp Preview", "ማህተሙን ይመልከቱ", "", "", "", "", ""],
  size: ["Size", "መጠን", "", "", "", ""],
  noStampUploaded: [
    "No stamps uploaded yet.",
    "ምንም አይነት ማህተም አልተጫነም",
    "",
    "",
    "",
    "",
  ],
  stampsOptional: [
    "Stamps are optional. You can add them later.",
    "ማህተሞች አማራጭ ናቸው. በኋላ መጨመር ይችላሉ.",
    "",
    "",
    "",
    "",
    "",
  ],
  receiverStrucucturesRecord: [
    "  Select structures that can receive forwarded documents from this record office. This step is optional.",
    "ከዚህ መዝገብ ቢሮ የተላለፉ ሰነዶችን መቀበል የሚችሉትን መዋቅሮች ይምረጡ። ይህ እርምጃ አማራጭ ነው.",
    "",
    "",
    "",
    "",
  ],
  selectAll: ["Select All", "ሁሉንም ይምረጡ", "", "", "", ""],
  deselectAll: ["Deselect All", "የምረጡትን ይሰርዙ", "", "", "", ""],
  availableStructures: ["Available Structures", "የሚገኙ መዋቅሮች", "", "", "", ""],
  noStructureFound: [
    "No structure found",
    "ምንም አይነት መዋቅር አልተገኘም",
    "",
    "",
    "",
    "",
    "",
    "",
  ],
  selectedReceivers: ["Selected Recipents", "የተመረጡ ተቀባዮች", "", "", "", ""],
  selected: ["Selected", "ተመርጧል", "", "", "", ""],
  more: ["More", "ተጨማሪ", "", "", "", ""],
  assignedRecordOffice: [
    "Select structures that are assigned to this record office. This step is optional.",
    "ለዚህ መዝገብ ቢሮ የተመደቡትን መዋቅሮች ይምረጡ። ይህ ድርጊት አማራጭ ነው",
    "",
    "",
    "",
    "",
  ],
  selectedStructures: ["Selected Structures", "የተመረጡ መዋቅሮች", "", "", "", ""],
  stampUpload: ["Stamp Upload", "ማህተም ይጫኑ", "", "", "", ""],
  recordOfficeNameEn: [
    "Record Office Name (English) *",
    "የመዝገብ ቤት ስም በኢንግሊዘኛ ያስገቡ *",
    "",
    "",
    "",
    "",
  ],

  recordOfficeNameAm: [
    "Record Office Name (Amharic) *",
    "የመዝገብ ቤት ስም በአማርኛ ያስገቡ *",
    "",
    "",
    "",
    "",
  ],

  recordOfficeNameOr: [
    "Record Office Name Afaan Oromo",
    "የመዝገብ ቤት ስም በኦሮሚፋ",
    "",
    "",
    "",
    "",
  ],

  recordOfficeNameTi: [
    "Record Office Name (Tigrinya)",
    "የመዝገብ ቤት ስም በትግርኛ",
    "",
    "",
    "",
    "",
  ],

  recordOfficeNameSo: [
    "Record Office Name (Somali)",
    "የመዝገብ ቤት ስም በትግርኛ (ሱማሊ)",
    "",
    "",
    "",
    "",
  ],

  recordOfficeNameAa: [
    "Record Office Name (Afar)",
    "የመዝገብ ቤት ስም በትግርኛ (በአፋር)",
    "",
    "",
    "",
    "",
  ],
  recordOfficeNameEnPlaceholder: [
    "Enter record office name in English",
    "የመዝገብ ቤት ስም በኢንግሊዘኛ ያስገቡ",
    "",
    "",
    "",
    "",
  ],

  recordOfficeNameAmPlaceholder: [
    "Enter record office name in Amharic",
    "የመዝገብ ቤት ስም በአማርኛ ያስገቡ",
    "",
    "",
    "",
    "",
  ],

  recordOfficeNameOrPlaceholder: [
    "Enter record office name in Afaan Oromo",
    "የመዝገብ ቤት ስም Afaan Oromo ያስገቡ",
    "",
    "",
    "",
    "",
  ],

  recordOfficeNameTiPlaceholder: [
    "Enter record office name in Tigrinya",
    "የመዝገብ ቤት ስም በትግርኛ ያስገቡ",
    "",
    "",
    "",
    "",
  ],

  recordOfficeNameSoPlaceholder: [
    "Enter record office name in Somali",
    "የመዝገብ ቤት ስም በሶማሊ ያስገቡ",
    "",
    "",
    "",
    "",
  ],

  recordOfficeNameAaPlaceholder: [
    "Enter record office name in Afar",
    "የመዝገብ ቤት ስም በአፋር ያስገቡ",
    "",
    "",
    "",
    "",
  ],
  editRecordOffice: ["Edit Record Office", "መዝገቤቱን ያዘምኑ", "", "", "", ""],
  addUserPosition: ["Add User Position", "የስራ መደብ ይመዝግቡ", "", "", "", ""],
  selectStructure: ["Select Structure", "መዋቅር ይምረጡ", "", "", "", "", ""],
  structureRequired: ["Structure is required", "መዋቅር አስፈላጊ ነው", "", "", "", ""],
  userRequired: ["User is required", "ተጠቃሚ አስፈላጊ ነው", "", "", "", ""],
  startDateRequired: [
    "Start date is required",
    "መነሻ ቀን አስፈልጊ ነው",
    "",
    "",
    "",
    "",
  ],
  endDate: ["End Date", "ማብቅያ ቀን", "", "", "", ""],
  endDateOptional: ["End Date (optional)", "የማብቂያ ቀን (በ ምርጫ)", "", "", "", ""],
  numberOfLines: ["Number of lines", "የመስመሮች ብዛት", "", "", "", ""],
  enterNumberOfLines: [
    "Enter number of lines",
    "የመስመሮች ብዛት ያስገቡ",
    "",
    "",
    "",
    "",
  ],
  positionTitleEn: [
    "Position Title (English)",
    "የስራ መደብ ርዕስ (እንግሊዝኛ)",
    "",
    "",
    "",
    "",
  ],

  positionTitleAm: [
    "Position Title (Amharic)",
    "የስራ መደብ ርዕስ (አማርኛ)",
    "",
    "",
    "",
    "",
  ],

  positionTitleOr: [
    "Position Title (Afaan Oromo)",
    "የስራ መደብ ርዕስ (Afaan Oromo)",
    "",
    "",
    "",
    "",
  ],

  positionTitleTi: [
    "Position Title (Tigrinya)",
    "የስራ መደብ ርዕስ (ትግርኛ)",
    "",
    "",
    "",
    "",
  ],

  positionTitleSo: [
    "Position Title (Somali)",
    "Cinwaanka jagada (Soomaali)",
    "",
    "",
    "",
    "",
  ],

  positionTitleAa: [
    "Position Title (Afar)",
    "Magaca jagada shaqo (Afar)",
    "",
    "",
    "",
    "",
  ],
  positionTitleEnPlaceholder: [
    "Enter position title in English",
    "የስራ መደብ ርዕስን በእንግሊዝኛ ያስገቡ",
    "",
    "",
    "",
    "",
  ],

  positionTitleAmPlaceholder: [
    "Enter position title in Amharic",
    "የስራ መደብ ርዕስን በአማርኛ ያስገቡ",
    "",
    "",
    "",
    "",
  ],

  positionTitleOrPlaceholder: [
    "Enter position title in Oromifa",
    "የስራ መደብ ርዕስን በኦሮሚፋ ያስገቡ",
    "",
    "",
    "",
    "",
  ],

  positionTitleTiPlaceholder: [
    "Enter position title in Tigrinya",
    "የስራ መደብ ርዕስን በትግርኛ ያስገቡ",
    "",
    "",
    "",
    "",
  ],

  positionTitleSoPlaceholder: [
    "Enter position title in Somali",
    "Geli cinwaanka jagada (Soomaali)",
    "",
    "",
    "",
    "",
  ],

  positionTitleAaPlaceholder: [
    "Enter position title in Afar",
    "Magaca jagada ku qor (Afar)",
    "",
    "",
    "",
    "",
  ],
  relieve: ["Relieve", "", "", "", "", ""],
  totalUserPositions: ["Total User Positions", "ጠቅላላ የስራ መደቦች", "", "", "", ""],
  createUserPositions: [
    "Create User Position",
    "የስራ መደብ ይመዝግቡ",
    "",
    "",
    "",
    "",
  ],
  noUserPositionFound: [
    "No user positions found",
    "ምንም አይነት የስራ መደቦች አልተገኘም",
    "",
    "",
    "",
    "",
  ],
  structure: ["Structure", "መዋቅር", "", "", "", ""],
  editUserPosition: ["Edit User Position", "የስራ መደቡን ያዘምኑ", "", "", "", "", ""],
};
