export const language = {
  fullAAHDC: [
    "Addis Ababa Housing Development Corporation",
    "አዲስ አበባ ቤቶች ልማት ኮርፖሬሽን",
    "",
    "",
    "",
    "",
  ],
  copyRightAAHDC: [
    "Addis Ababa Housing Development Corporation © 2025. All Rights Reserved",
    "የአዲስ አበባ ቤቶች ልማት ኮርፖሬሽን © 2025. መብቱ በህግ የተጠበቀ ነው።",
  ],
  AASTU: [
    "Addis Ababa Science and Technology University",
    "በአዲስ አበባ ሳይንስና ቴክኖሎጂ ዩኒቨርሲቲ ",
  ],
  poweredBy: ["Powered By", "የበለጸገ"],
  systemName: [
    "customer service, complaint and accusation system",
    "የደንበኞች አገልግሎት፣ የቅሬታና የጥቆማ ማቅረቢያ ሥርዓት",
    "Sagantaa Tajaajila Maamilaa, Komii fi Eeruu Dhiyeessuu",
    "ሲስተም ኣገልግሎት ተጠቀምቲ፣ ቅሬታን ጥቆማን ምቕራብ",
    "",
    "",
  ],
  submitAccusation: [
    "Submit An Accusation",
    "ጥቆማ ያቅርቡ",
    "Eeruu Galchaa",
    "ጥቆማ ኣቕርቡ",
    "",
    "",
  ],
  accusationInformation: [
    "Accusation Information",
    "የጥቆማ መረጃ",
    "Odeeffannoo Eeruu",
    "ሓበሬታ ጥቆማ",
    "",
    "",
    "",
  ],
  home: ["Home", "ዋና ገጽ", "Fuula Ijoo", "ዋና ገጽ", "", ""],
  services: ["Services", "አገልግሎቶች", "Tajaajiloota", "ኣገልግሎታት", "", ""],
  organizations: [
    "Organizations",
    "ተቋማት",
    "Hundeeffamoota/Dhaabbilee",
    "ትካላት",
    "",
    "",
  ],
  support: ["Support", "ድጋፍ", "Deeggarsa", "ደገፍ", "", ""],
  faq: [
    "FAQ",
    "በተጋጋሚ የተጠየቁ ጥያቄዎች",
    "Gaaffiiwwan Yeroo Baay'ee Gaafataman",
    "ብተደጋጋሚ ዝሕተቱ ሕቶታት",
    "",
    "",
  ],
  contact: ["Contact Us", "አግኙን", "Nu Quunnamaa", "ኣዘራርቡና", "", ""],
  checkCaseStatus: [
    "Check Case Status",
    "የጉዳዮን ሁኔታ ይከታተሉ",
    "Haala Dhimmaa Keessanii Hordofaa",
    "ኩነታት ጉዳይኩም ተኸታተሉ",
    "",
    "",
  ],
  applyCase: [
    "Apply a Case",
    "ጉዳይ ያመልክቱ",
    "Dhimma Iyyadhaa",
    "ጉዳይ ኣቕርቡ",
    "",
    "",
  ],
  caseStatusDescription: [
    "Do you want to know the progress of your case? Enter your case details and instantly see its current status.",
    "የጉዳዮዎን ሂደት ማወቅ ይፈልጋሉ? የጉዳይ ዝርዝሮችን ያስገቡ እና ወዲያውኑ አሁን ያለበትን ሁኔታ ይወቁ።",
    "Adeemsa Dhimma Keessanii Beektuu Barbaadduu? Ibsa dhimmaa galchaatii battalumatti haala isaa amma jiru ilaalaa.",
    "መስርሕ ጉዳይኩም ክትፈልጡ ትደልዩ'ዶ? ዝርዝር ጉዳይኩም ኣእትዉ እሞ ብቕጽበት ዘለዎ ኩነታት ተመልከቱ።",
    "",
    "",
  ],
  applyCaseDescription: [
    "Need to start a new case? Verify your identity, choose a service, answer a few quick questions, and get confirmation.",
    "አዲስ ጉዳይ ማመልከት ይፈልጋሉ? ማንነትዎን ያረጋግጡ፣ አገልግሎት ይምረጡ፣ ጥቂት ጥያቄዎችን ይመልሱ እና ማረጋገጫ ያግኙ።",
    "Dhimma Haaraa Eegaluu Barbaadduu? Eenyummee keessan mirkaneeffadhaa, tajaajila filadhaa, gaaffii gaggabaaboo muraasaaf deebii kennaatii mirkaneeffannaa argadhaa.",
    "ሓድሽ ጉዳይ ክትጅምሩ ትደልዩዶ? መንነትኩም ኣረጋግጹ፣ ኣገልግሎት ምረጹ፣ ንሓጺር ሕቶታት መልሱ እሞ መረጋገጺ ረኽቡ።",
  ],
  accusationDescription: [
    "Have an issue or complaint to report? Provide the details and submit your accusation for official review.",
    "የሚዘግቡት ችግር ወይም ቅሬታ አለዎት? ዝርዝሮችን ያቅርቡ እና ለይፋዊ ግምገማ ጥቆማዎን ያስገቡ።",
    "Rakkoo yookiin komii gabaasuu qabduu? Ibsa kennaatii eeruu keessan qorannoo ofiisaa akka argatuuf galchaa.",
    "ክትሕብሩዎ ትደልዩዎ ጸገም ወይ ቅሬታ ኣለኩምዶ? ዝርዝራት ሃቡ እሞ ጥቆማኹም ንወግዓዊ ምርመራ ኣቕርቡ።",
  ],
  readMore: ["Read More", "ተጨማሪ ያንብቡ", "Dabalata Dubbisaa", "ዝያዳ ኣንብብ", "", ""],
  loading: [
    "Loading...",
    "በሂደት ላይ...",
    "Hojii Irratti Jira...",
    "ኣብ መስርሕ...",
    "",
    "",
  ],
  showMoreServices: [
    "Show more services",
    "ተጨማሪ አገልግሎቶችን አሳይ",
    "Tajaajiloota Dabalataa Agarsiisi",
    "ተወሳኺ ኣገልግሎታት ኣርኢ",
    "",
    "",
  ],
  email: ["Email", "ኢሜይል", "Iimeelii", "ኢሜይል", "", ""],
  phone: ["Phone", "ስልክ ቁጥር", "Lakkoofsa Bilbilaa", "ቍጽሪ ስልኪ", "", ""],
  ourOfficalWebsite: [
    "Our Officeal Website",
    "የእኛ ይፋዊ ድህረ ገጽ",
    "Marsariitii Ofiisaa Keenya",
    "ወግዓዊ ወብሳይትና",
    "",
    "",
  ],
  quickLinks: [
    "Quick Links",
    "ፈጣን መዳረሻዎች",
    "Hidhaalee Ariifachiisoo",
    "ቅልጡፍ መተሓሓዝቲ",
    "",
    "",
  ],
  incidentDate: [
    "Incident Date",
    "የክስተቱ ቀን",
    "Guyyaa Taatee",
    "ዕለት ፍጻሜ",
    "",
    "",
  ],
  selectDate: ["Select date", "ቀን ይምረጡ", "Guyyaa Filadhaa", "ዕለት ምረጽ", "", ""],
  location: ["Location", "ቦታ", "Iddoo", "ቦታ", "", ""],
  enterLocation: [
    "Enter the place where the incident took place",
    "ክስተቱ የተፈጸመበትን ቦታ ያስገቡ",
    "Iddoo taateen itti raawwate galchaa",
    "ፍጻሜው ዝተፈጸመሉ ቦታ ኣእትው",
  ],
  subject: ["Subject", "ጉዳዩ", "Mata Duree", "ጉዳዩ", "", ""],
  organization: ["Organization", "ተቋም", "Dhaabbata/Hundeeffama", "ትካል", "", ""],
  city: ["City", "ከተማ", "Magaalaa", "ከተማ", "", ""],
  subcity: ["Sub City", "ክ/ከተማ", "Kutaa Magaalaa", "ክፍለ ከተማ", "", ""],
  woreda: ["Woreda", "ወረዳ", "Aanaa", "ወረዳ", "", ""],
  specialname: [
    "Special Place Name (optional)",
    "ልዩ የቦታ ስም (አማራጭ)",
    "Maqaa Iddoo Addaa (Filannoodha)",
    "ፍሉይ ስም ቦታ (ብምርጫ)",
    "",
    "",
  ],
  enterSpecialName: [
    "Enter any special place name if applicable",
    "ተገቢ ከሆነ ማንኛውንም ልዩ የቦታ ስም ያስገቡ",
    "Yoo ta'e, maqaa iddoo addaa kamiyyuu galchaa",
    "ተገቢ እንተኾይኑ፡ ዝኾነ ይኹን ፍሉይ ስም ቦታ ኣእትዉ",
    "",
    "",
  ],
  description: ["Description", "ማብራሪያ", "Ibsa", "መግለጺ", "", ""],
  contactInformation: [
    "Contact Information (Optional)",
    "የመገኛ መረጃ (አማራጭ)",
    "Odeeffannoo Quunnamtii (Filannoodha)",
    "ሓበሬታ መዘራረቢ (ብምርጫ)",
    "",
    "",
  ],
  name: ["Your Name", "የእርሶ ስም", "Maqaa Keessan", "ሽምኩም", "", ""],
  enterName: [
    "Enter your name",
    "ሙሉ ስም ያስገቡ",
    "Maqaa keessan guutuu galchaa",
    "ሙሉእ ሽምኩም ኣእትዉ",
    "",
    "",
  ],
  phoneNUmber: [
    "Phone Number",
    "ስልክ ቁጥር",
    "Lakkoofsa Bilbilaa",
    "ቍጽሪ ስልኪ",
    "",
    "",
  ],
  enterPhoneNumber: [
    "Enter your phone number",
    "ስልክ ቁጥር ያስገቡ",
    "Lakkoofsa bilbilaa keessan galchaa",
    "ቍጽሪ ስልኪኹም ኣእትዉ",
    "",
    "",
  ],
  uploadEvidence: [
    "Upload Evidence (optional)",
    "ማስረጃ ይጫኑ (አማራጭ)",
    "Ragaa Ol Baasaa (Filannoodha)",
    "መረጋገጺ ስቀል (ብምርጫ)",
    "",
    "",
    "",
  ],
  acceptedFormatDoc: [
    "Accepted Formats: PDF (MAX 100MB)",
    "የተፈቀደው ፎርማት፡ ፒዲኤፍ (ከ100ሜባ መብለጥ የለበትም)",
    "Foormaatota Fudhatamoo: PDF (Baay’ina Guddaa 100MB)",
    "ተቐባልነት ዘለዎም ቅርጺታት: ፒዲኤፍ (ብዝበለጸ 100ሜባ)",
    "",
    "",
  ],
  acceptedFormatMedia: [
    "Accepted Formats: JPG, PNG, MP4, MPEG, MP3, MKV (Max 500MB)",
    "የተፈቀደው ፎርማት፡ JPG, PNG, MP4, MPEG, MP3, MKV (ከ500ሜባ መብለጥ የለበትም)",
    "Foormaatota Fudhatamoo: JPG, PNG, MP4, MPEG, MP3, MKV (Baay’ina Guddaa 500MB)",
    "ተቐባልነት ዘለዎም ቅርጺታት: JPG, PNG, MP4, MPEG, MP3, MKV (ብዝበለጸ 500ሜባ)",
    "",
    "",
  ],
  selectOrg: [
    "Select Organization",
    "ተቋም ይምረጡ",
    "Hundeeffama Filadhaa",
    "ትካል ምረጽ",
    "",
    "",
  ],
  checkCaseProgress: [
    "check the progress of the case you applied to",
    "ያመለከቱበትን ጉዳይ ሂደት ይመልከቱ",
    "Adeemsa dhimma iyyattaniif ilaalaa",
    "መስርሕ እቲ ዘቕረብኩምዎ ጉዳይ ተመልከቱ",
  ],
  enterCaseNumber: [
    "Enter Case Number",
    "የጉዳይ ቁጥርዎን ያስገቡ",
    "Lakkoofsa Dhimmaa Keessan Galchaa",
    "ቍጽሪ ጉዳይኩም ኣእትዉ",
    "",
    "",
  ],
  caseNumber: [
    "Case Number",
    "የጉዳይ ቁጥር",
    "Lakkoofsa Dhimmaa",
    "ቍጽሪ ጉዳይ",
    "",
    "",
  ],
  viewCase: [
    "View Case Status",
    "የጉዳዮን ሁኔታ ይመልከቱ",
    "Haala Dhimmaa Ilaalaa",
    "ኩነታት ጉዳይ ተመልከት",
    "",
    "",
  ],
  searchService: [
    "Search Service",
    "አገልግሎት ይፈልጉ",
    "Tajaajila Barbaadaa",
    "ኣገልግሎት ድለ",
    "",
    "",
  ],
  notStrcutOrgFound: [
    "The selected organization has no structures.",
    "የተመረጠው ተቋም ምንም ዓይነት መዋቅር የለውም።",
    "Hundeeffamni filatame tokkollee madaala hin qabu.",
    "እቲ ዝተመርጸ ትካል ዝኾነ ዓይነት መዋቕር የብሉን።",
    "",
    "",
  ],
  chooseService: [
    "Choose Service",
    "አገልግሎት ይምረጡ",
    "Tajaajila Filadhaa",
    "ኣገልግሎት ምረጽ",
    "",
    "",
  ],
  errorOccured: [
    "Something went wrong. Please try again later",
    "ችግር ተፈጥሯል። እባክዎ ቆይተው እንደገና ይሞክሩ።",
    "Dogoggorri uumameera. Maaloo booda deebisaanii yaalaa.",
    "ጸገም ኣጋጢሙ። እባክዎ ድሕሪት መሊስኩም ፈትኑ።",
    "",
    "",
  ],
  serviceRequest: [
    "Service Questionaire",
    "የአገልግሎት መጠይቅ",
    "Gaaffiiwwan Tajaajilaa",
    "ሕቶታት ኣገልግሎት",
    "",
    "",
  ],
  verification: [
    "Identity Verification",
    "የማንነት ማረጋገጫ",
    "Mirkaneeffannaa Eenyummee",
    "መረጋገጺ መንነት",
    "",
    "",
  ],
  servicePayment: [
    "Service Payment",
    "የአገልግሎት ክፍያ",
    "Kaffaltii Tajaajilaa",
    "ክፍሊት ኣገልግሎት",
    "",
    "",
  ],
  caseApplication: [
    "Case Application",
    "የጉዳይ ማመልከቻ",
    "Iyyannoo Dhimmaa",
    "ምምልካት ጉዳይ",
    "",
    "",
  ],
  chooseCaseApply: [
    "Choose the case you want to apply to.",
    "ለማመልከት የሚፈልጉትን አገልግሎት ይምረጡ።",
    "Dhimma iyyachuu barbaaddan filadhaa.",
    "እትምልከትሉ/እትቀርቡሉ ትደልዩ ጉዳይ ምረጹ።",
    "",
    "",
  ],
  prerequsiteWarnning: [
    "I confirm that I have read and understood the above requirements and will provide accurate information with valid documents.",
    "ሁሉንም መስፈርቶች ማሟላቴን፣ እንዲሁም ትክክለኛ መረጃ እና ሕጋዊ ሰነዶችን እንደማቀርብ አረጋግጣለሁ።",
    "Ulaagaalee olii dubbisuu fi hubachuu koo akkasumas odeeffannoo sirrii fi sanadoota seera qabeessa dhiyeessuu koo mirkaneeffadheera.",
    "ኩሎም መዐቀንታት ከም ዝማልኡ፡ ከምኡ'ውን ቅኑዕ ሓበሬታን ሕጋዊ ሰነዳትን ከምዘቕርብ ኣረጋግጽ።",
  ],
  prerequsiteNotice: [
    "Prerequisite Notice - Read Before Starting",
    "ቅድመ ሁኔታ ማሳሰቢያ፤ የሚከተሉትን ማሟላትዎን ያረጋግጡ:",
    "Hubannoo Ulaagaalee Duraa - Duraan Dura Dubbisaa",
    "ቅድመ ኲነታት መዘኻኸሪ - ቅድሚ ምጅማርኩም ኣንብቡ",
    "",
    "",
  ],
  proceed: ["Procced", "ይቀጥሉ", "Itti Fufaa", "ቀጽል", "", ""],
  previous: ["Previous", "ቀዳሚ", "Duraan Dursee", "ቀዳማይ", "", ""],
  next: ["Next", "ቀጣይ", "Itti Aanu", "ቀጣይ", "", ""],
  step: ["Step", "ደረጃ", "Sadarkaa", "ደረጃ", "", ""],
  selectSector: [
    "Please Select a Sector",
    "እባክዎን ዘርፍ ይምረጡ",
    "Maaloo Damee Filadhaa",
    "በጃኹም ዘርፊ ምረጹ",
    "",
    "",
  ],
  choose: ["Choose", "ይምረጡ", "Filadhaa", "ምረጽ", "", ""],
  noFileChosen: [
    "No File Chosen",
    "ምንም ፋይል አልተመረጠም",
    "Faayiliin Tokkollee Hin Filatamne",
    "ዝኾነ ፋይል ኣይተመርጸን",
    "",
    "",
  ],
  caseForm: ["Case Form", "የጉዳይ ቅጽ", "Foormii Dhimmaa", "ቅጥዒ ጉዳይ", "", ""],
  readAllQuestions: [
    "Read and answer all questions.",
    "ሁሉንም ጥያቄዎች ያንብቡ እና ይመልሱ።",
    "Gaaffii hundumaa dubbisaatii deebisaa.",
    "ኩሎም ሕቶታት ኣንቢብኩም መልሱ።",
  ],
  getInTouch: ["Get In Touch", "ያግኙን", "Quunnamtii Uumaa", "ኣዘራርቡና", "", ""],
  fayda: [
    "National ID (Fayda) Verification",
    "ብሔራዊ መታወቂያ (ፋይዳ) ማረጋገጫ",
    "Mirkaneeffannaa Eenyummee Biyyaa (Faayidaa)",
    "መረጋገጺ ሃገራዊ መንነት (ፋይዳ)",
    "",
    "",
  ],
  Fin: ["FIN", "FIN", "FIN", "FIN", "", ""],
  chooseMethod: [
    "Choose Verification Method",
    "የማረጋገጫ አማራጭ ይምረጡ",
    "Tooftaa Mirkaneeffannaa Filadhaa",
    "ኣማራጺ መረጋገጺ ምረጹ",
    "",
    "",
  ],
  chooseMethodDescription: [
    "Verify your identity using your National ID or your phone number",
    "ማንነትዎን ብሔራዊ መታወቂያዎን ወይም ስልክ ቁጥርዎን በመጠቀም ያረጋግጡ።",
    "Eenyummee keessan Eenyummee Biyyaa yookiin lakkoofsa bilbilaa keessan fayyadamuun mirkaneeffadhaa.",
    "መንነትኩም ብምጥቃም ሃገራዊ መንነትኩም ወይ ቁጽሪ ስልኪኹም ኣረጋግጹ።",
    "",
    "",
  ],
  nationalID: [
    "National ID",
    "ብሔራዊ መታወቂያ (ፋይዳ)",
    "Eenyummee Biyyaa (Faayidaa)",
    "ሃገራዊ መንነት (ፋይዳ)",
    "",
    "",
  ],
  enterNationalID: [
    "Enter your National ID (FIN).",
    "ብሔራዊ መታወቂያ ቁጥርዎን (FIN) ያስገቡ።",
    "Lakkoofsa Eenyummee Biyyaa keessan (FIN) galchaa.",
    "ቍጽሪ ሃገራዊ መንነትኩም (FIN) ኣእትዉ።",
    "",
    "",
  ],
  verify: ["Verify", "ያረጋግጡ", "Mirkaneeffadhaa", "ኣረጋግጽ", "", ""],
  smsMessage: [
    "An SMS will be sent to the phone number.",
    "ከብሔራዊ መታወቂያዎ ጋር በተገናኘው ስልክ ቁጥር የጽሑፍ መልዕክት ይላካል።",
    "Ergaan gabaabaan lakkoofsa bilbilaatti ergama.",
    "መልእኽቲ ጽሑፍ ናብ ቁጽሪ ስልኪ ክስደድ እዩ።",
    "",
    "",
  ],
  casePhoneNumber: [
    "Enter Your Phone Number And Apply your case",
    "ስልክ ቁጥርዎን ያስገቡ እና ለጉዳይዎ ይመዝገቡ",
    "Lakkoofsa Bilbilaa Keessan Galchaatii Dhimma Keessan Iyyadhaa",
    "ቍጽሪ ስልኪኹም ኣእትዉ እሞ ጉዳይኩም ኣቕርቡ",
    "",
    "",
  ],
  fullname: ["Full Name", "ሙሉ ስም", "Maqaa Guutuu", "ሙሉእ ስም", "", ""],
  enterFullName: [
    "Enter your full name",
    "ሙሉ ስምዎን ያስገቡ",
    "Maqaa keessan guutuu galchaa",
    "ሙሉእ ስምኩም ኣእትዉ",
    "",
    "",
  ],
  gender: ["Gender", "ጾታ", "Saala", "ጾታ", "", ""],
  chooseGender: [
    "Choose Gender",
    "ጾታ ይምረጡ",
    "Saala Filadhaa",
    "ጾታ ምረጽ",
    "",
    "",
  ],
  houseNumber: ["House Number", "የቤት ቁጥር", "Lakkoofsa Manaa", "ቍጽሪ ቤት", "", ""],
  residentialID: [
    "Upload your residential ID",
    "የመኖሪያ መታወቂያዎን ያያይዙ",
    "Eenyummee Jiraattotaa keessan Ol Baasaa",
    "መንነት ምንባርኩም ስቀሉ",
    "",
    "",
  ],
  male: ["Male", "ወንድ", "Dhiira", "ተባዕታይ", "", ""],
  female: ["Female", "ሴት", "Dubartii", "ኣንስተይቲ", "", ""],
  paymentMethod: [
    "Payment Method",
    "የክፍያ አማራጭ",
    "Tooftaa Kaffaltii",
    "ኣማራጺ ክፍሊት",
    "",
    "",
  ],
  paymentFee: [
    "Payment Fee Amount",
    "የክፍያ መጠን",
    "Baay'ina Kaffaltii",
    "መጠን ክፍሊት",
    "",
    "",
  ],
  serviceInformation: [
    "Service Information",
    "የአገልግሎት መረጃ",
    "Odeeffannoo Tajaajilaa",
    "ሓበሬታ ኣገልግሎት",
    "",
    "",
  ],
  division: ["Division", "ዘርፍ", "Damee", "ዘርፊ", "", ""],
  case: ["Case", "ጉዳይ", "Dhimma", "ጉዳይ", "", ""],
  submittedForm: [
    "Submitted Form",
    "የቀረበው ቅጽ",
    "Foormii Dhiyeessame",
    "ዝቐረበ ቅጥዒ",
    "",
    "",
  ],
  confirmPayment: [
    "Confirm Payment",
    "ክፍያውን ያረጋግጡ",
    "Kaffaltii Mirkaneeffadhaa",
    "ክፍሊት ኣረጋግጽ",
    "",
    "",
  ],
  caseApplicationStatus: [
    "Case Application Success",
    "የጉዳይ ማስገባት በተሳካ ሁኔታ ተጠናቋል",
    "Galmeen Dhimmaa Milkaa'inaan Xumurameera",
    "ምምልካት ጉዳይ ብዓወት ተዛዚሙ",
  ],
  successMessage: [
    "Congratulations! You have successfully submitted your case.",
    "እንኳን ደስ አልዎት! ጉዳይዎን በተሳካ ሁኔታ አስገብተዋል።",
    "Baga Gammaddan! Dhimma keessan milkaa'inaan galchitanii jirtu.",
    "እንኳን ደስ ኣበለኩም! ጉዳይኩም ብዓወት ኣቕሪብኩም ኣለኹም።",
  ],
  returnMainPage: [
    "Return to home page",
    "ወደ ዋና ገጽ ይመለሱ",
    "Gara Fuula Ijoo Deebi'aa",
    "ናብ ዋና ገጽ ተመለስ",
    "",
    "",
  ],
};
